### ISSUE TITLE
Small thing with getVectorParameter

### ISSUE THREAD

**Issue by gvbarroso** [BioPP/bpp-core#18]
Please note that using SPACE as the separator argument results in bad behaviour without throwing any errors.

**Comment by lgueguen** [comment]
Hi,

thanks for the report. However, could you please be more descriptive about the "bad behaviour"? 

Cheers,
Laurent

**Comment by jydu** [comment]
Hi Laurent,

what happens is that spaces are removed before parsing, and therefore the vector content is concatenated. I think we should just not allow spaces as a delimiter and throw an exception in case. I can implement it if you agree.

J.

**Comment by lgueguen** [comment]
Okay, this is fine for me.

L
