### ISSUE TITLE
static vs shared library build

### ISSUE THREAD

**Issue by igel-kun** [BioPP/bpp-core#24]
Hi,
I was slightly confused when installing `bpp-*` that the compile went through twice.
It seems that, by default, static AND shared libraries are installed.
It there an easy way to configure the build system to only compile and install the shared libraries (and headers)?
Would a pull-request implementing this be welcomed?

cheers

**Comment by jydu** [comment]
Hi,

Actually, there is... I have added a BUILD_STATIC argument to the CMakeList. By default, static libs will not be compiled and installed. Setting it to YES will compile them and install them. I have added this to bpp-core only for now, can you check whether that would do what you need? If yes, I can modify the other libraries accordingly.

Julien.

**Comment by igel-kun** [comment]
Ah I see it now, cool thanks. Just a couple of quick questions about it:
1. if I build with `BUILD_STATIC=YES`, will the static AND shared libraries be built or just the static one?
2. at first glance, I kind of expected this to also influence https://github.com/BioPP/bpp-core/blob/84a99c4e38705ca16bc1caea359db440d3dfe871/package.cmake.in#L15 but maybe I am wrong about that...

**Comment by jydu** [comment]
BUILD_STATIC=YES will build both static and dynamic libraries.
